"""
§11.4 Alerts — Gmail via smtplib + App Password.

Requires env vars:
  GMAIL_TO           — recipient address
  GMAIL_FROM         — sender address (usually same as GMAIL_TO)
  GMAIL_APP_PASSWORD — 16-char app password from https://myaccount.google.com/apppasswords
"""

from __future__ import annotations

import json
import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

log = logging.getLogger(__name__)

GMAIL_TO = os.getenv("GMAIL_TO", "")
GMAIL_FROM = os.getenv("GMAIL_FROM", "") or GMAIL_TO
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def _format_decision_table(decisions: dict[str, Any]) -> str:
    lines = []
    for ticker, d in decisions.items():
        if isinstance(d, dict):
            action = d.get("action", "?")
            conf = d.get("confidence", "?")
            lines.append(f"  {ticker:6s} → {action:5s} (confidence: {conf})")
    return "\n".join(lines) or "  (no decisions)"


def _format_report(results: dict[str, Any], cycle_id: str, trade_date: str) -> tuple[str, str]:
    """Build subject + body."""
    decisions = results.get("decisions", {})
    errors = results.get("errors", {})
    latency = results.get("latency", {})

    actions_summary = ", ".join(
        f"{t}:{d.get('action', '?')}" for t, d in decisions.items() if isinstance(d, dict)
    )
    subject = f"[QTA] {trade_date} — {actions_summary or 'no decisions'}"

    body = f"""Quantum Trading Agent — Daily Report
{'=' * 50}

Date:     {trade_date}
Cycle:    {cycle_id}
Tickers:  {', '.join(decisions.keys()) or 'none'}

DECISIONS
{'-' * 30}
{_format_decision_table(decisions)}

"""
    for ticker, d in decisions.items():
        if isinstance(d, dict) and d.get("reasoning"):
            body += f"\n--- {ticker} — {d.get('action', '?')} (confidence: {d.get('confidence', '?')}) ---\n"
            body += d.get("reasoning", "") + "\n"
            if d.get("risk_notes"):
                body += f"\nRisk: {d['risk_notes']}\n"

    if errors:
        body += f"\nERRORS\n{'-' * 30}\n"
        for ticker, err in errors.items():
            body += f"  {ticker}: {err}\n"

    if latency and latency.get("count", 0) > 0:
        body += f"\nLATENCY (last 24h)\n{'-' * 30}\n"
        body += f"  Pipeline p50: {latency.get('pipeline_duration_ms_p50', 'N/A')}ms\n"
        body += f"  Pipeline p95: {latency.get('pipeline_duration_ms_p95', 'N/A')}ms\n"

    body += "\n--\nGenerated by Quantum Trading Agent\n"
    return subject, body


def _send_email(subject: str, body: str) -> bool:
    """Send email via Gmail SMTP + App Password."""
    if not GMAIL_TO or not GMAIL_APP_PASSWORD:
        log.warning("Gmail not configured (GMAIL_TO or GMAIL_APP_PASSWORD missing); skipping email")
        return False

    msg = MIMEMultipart()
    msg["From"] = GMAIL_FROM
    msg["To"] = GMAIL_TO
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain", "utf-8"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(GMAIL_FROM, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_FROM, [GMAIL_TO], msg.as_string())
        log.info("Email sent: %s → %s", subject, GMAIL_TO)
        return True
    except Exception as e:
        log.error("Email send failed: %s", e)
        return False


def send_gmail_report(results: dict[str, Any], cycle_id: str, trade_date: str) -> bool:
    """Format + send the daily report email."""
    subject, body = _format_report(results, cycle_id, trade_date)
    return _send_email(subject, body)


def alert_decision(decision: dict[str, Any]) -> None:
    """Log decision summary (real-time alert during pipeline)."""
    log.info(
        "ALERT [decision] %s → %s (confidence: %s)",
        decision.get("ticker"), decision.get("action"), decision.get("confidence"),
    )


def alert_error(ticker: str, error: Exception) -> None:
    """Critical error — immediate notification."""
    log.error("ALERT [error] %s: %s", ticker, error)
    # Send immediate error email
    _send_email(
        f"[QTA] ERROR: {ticker}",
        f"Pipeline error for {ticker}:\n\n{error}",
    )


def alert_cost(call_count: int) -> None:
    """Call count threshold breached."""
    log.warning("ALERT [cost] Daily CLI calls at %d", call_count)
